### PR TITLE
Additional properties in v140 should not be allowed, except for sub properties of "_comment"

### LINKED ISSUE #12: Additional properties should not be allowed
add `"additionalProperties": false` to the respectivde items in `schema.json`

### PR DESCRIPTION
**Pull request by 4lm**
Closes #12 

Hi all,

what do you think? Mandatory properties for some objects in metadata? Yes, no, maybe :wink: 

Let's discuss!

Context: (i) https://github.com/OpenEnergyPlatform/metadata/issues/9#issuecomment-551908556, (ii) https://github.com/OpenEnergyPlatform/metadata/issues/9#issuecomment-551925124

### CODE REVIEW

**Comment by 4lm** [comment]
- Commit for discussing required properties: https://github.com/OpenEnergyPlatform/metadata/pull/11/commits/89d94ea891285be31096d704428e751f814b36dc
- Commit for discussing to not allow non-defined (additional) properties: https://github.com/OpenEnergyPlatform/metadata/pull/11/commits/581dde677e88d8a55568ffdc25087860a5e9bee2

**BTW:** all changes on the schemas v130 and v140 are compatible with the given templates and examples of v130 and v140 (no changes where necessary or made to the templates or examples), so if all given metadata (v130 and v140) complies with the example and/or template of the specific version, they should validate against the schemas out-of-the-box, no changes needed! Hopefully :wink:

**Comment by wingechr** [comment]
As per our discussion at the meeting in Berlin today, all no additional properties (or sub properties) should be allowed, except for sub properties of "_comment".

**Comment by christian-rli** [comment]
It was my understanding that no fields should be required. At least @Ludee and I has always communicated on this premise. Any requirement might put off potential users (and we'd rather have someone fill out a single field than no field), so we thought there should be none whatsoever.

**Comment by Bachibouzouk** [comment]
@4lm I would say that the PR is not related to the issue you indicated this PR should close : the issue is "Additional properties should not be allowed" and the PR is about required properties. I'd suggest to remove the commits about the required properties and keep the ones about forbidding additional properties

**Comment by 4lm** [comment]
Sorry for the confusion, @Bachibouzouk I will do it like you suggested!

**Comment by 4lm** [comment]
Mhh, I wanted to rename the branch name to better reflect the topic of the PR. This is not working, GitHub closed the PR in didn't move the PR to the new branch `feature/don-t-allow-additional-properties`. So I restored the old branch and reopened this issue. And will remove the above mentioned commit on the old branch ...

**Comment by 4lm** [comment]
Done :) Please review!

**Pull request merged**
